### ISSUE TITLE
Understanding the experiments

### ISSUE THREAD

**Issue by zhang-jian** [Vaidehi99/OBPE#1]
Hi, thanks for the work. I have a question about the experiment section in the paper.

You mentioned 
`BALANCED : all three HRLs get 160K documents each`
`SKEWED : English gets one million, French half million, and Hindi 160K documents.`
In the result tables, you also mentioned several setups, e.g. `Balanced-4`, `Balanced-12` and `Skewed-12`. What are the 4 and 12 mean here? Thanks

**Comment by Vaidehi99** [comment]
Hi, thanks for reaching out. Balanced-4 setting involves training 3 separate models with 4 languages each (1 HRL and 3 LRLs) from the same family corresponding to each row in Table 2 of the paper. Balanced-12 setting involves training a single model with all 12 languages. I hope this makes it clear.
